# Funding options for the Global Shapers Hub Website Template

# GitHub Sponsors (if available)
# github: [global-shapers]

# Open Collective
# open_collective: global-shapers-template

# Custom funding URLs
custom: ["https://coff.ee/skansal"]

# Note: This is an open-source project created by Global Shapers London Hub III
# for the benefit of the entire Global Shapers community worldwide.
# 
# If this template has helped your hub, consider:
# - Contributing back to the project
# - Sharing your customizations with the community
# - Supporting the Global Shapers Community
# - Donating to your local hub's initiatives 
