name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run linting
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Check for build artifacts
      run: |
        if [ ! -d ".next" ]; then
          echo "Build failed - .next directory not found"
          exit 1
        fi
        echo "Build successful"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Check for vulnerabilities
      run: npm audit --audit-level=high --production

  validate-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate configuration files
      run: |
        # Check if required configuration files exist
        if [ ! -f "src/lib/settings.ts" ]; then
          echo "Error: settings.ts not found"
          exit 1
        fi
        
        if [ ! -f "src/lib/texts.ts" ]; then
          echo "Error: texts.ts not found"
          exit 1
        fi
        
        echo "Configuration files validated"
        
    - name: Check documentation
      run: |
        # Ensure key documentation files exist
        if [ ! -f "README.md" ]; then
          echo "Error: README.md not found"
          exit 1
        fi
        
        if [ ! -f "docs/SETUP.md" ]; then
          echo "Error: SETUP.md not found"
          exit 1
        fi
        
        echo "Documentation files validated"

  accessibility:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: npm start &
      
    - name: Wait for application to start
      run: sleep 10
      
    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli
      
    - name: Run Lighthouse CI
      run: |
        lhci autorun --config='{
          "ci": {
            "collect": {
              "url": ["http://localhost:3000"],
              "numberOfRuns": 1
            },
            "assert": {
              "assertions": {
                "categories:accessibility": ["error", {"minScore": 0.9}],
                "categories:best-practices": ["error", {"minScore": 0.8}],
                "categories:seo": ["error", {"minScore": 0.8}]
              }
            }
          }
        }' 